name: metafold

task_name: ${name}

shape_meta: &shape_meta
  obs:
    point_cloud:
      shape: [2048, 3]
      type: point_cloud
    language_emb:
      shape: [4096]
      type: low_dim
  action:
    shape: [12]

env_runner:
  _target_: diffusion_policy_3d.env_runner.metaworld_runner.MetaworldRunner
  eval_episodes: 20
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  fps: 10
  n_envs: null
  n_train: null
  n_test: null
  task_name: ${task_name}
  device: ${training.device}
  use_point_crop: ${policy.use_point_crop}

dataset:
  _target_: diffusion_policy_3d.dataset.metafold_dataset.MetafoldDataset
  zarr_path: /data2/xzhixuan/projects/3D-Diffusion-Policy/data/dp3_train_dataset.zarr
  horizon: ${horizon}  
  pad_before: ${eval:'${n_obs_steps}-1'} 
  pad_after: ${eval:'${n_action_steps}-1'}  
  seed: 42
  val_ratio: 0.0
  max_train_episodes: null
